name: olaf
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  marquee: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/user.json
    - assets/lexica.json
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
