name: olaf
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  marquee: ^2.0.4
  fading_edge_scrollview: ^3.0.0
  flutter_riverpod: ^2.0.0
  amazon_cognito_identity_dart_2: ^3.1.1
  amplify_api: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_flutter: ^2.0.0
  flutter_localizations:
    sdk: flutter
  horizontal_blocked_scroll_physics: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/user.json
    - assets/lexica.json
    - assets/uk.png
    - assets/fr.png
    - assets/de.png
    - assets/lang/en.json
    - assets/lang/fr.json
    - assets/lang/de.json
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
