name: olaf

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  fading_edge_scrollview: ^4.1.1
  flutter_riverpod: ^2.0.0
  flutter_localizations:
    sdk: flutter
  horizontal_blocked_scroll_physics: ^4.0.1
  camera: ^0.11.0+1
  path_provider: ^2.1.4
  aws_dynamodb_api: ^2.0.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  amazon_cognito_identity_dart_2: ^3.1.1
  amplify_api: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_flutter: ^2.3.0
  amplify_storage_s3: ^2.3.0
  tuple: ^2.0.2
  permission_handler: ^11.3.1
  dio: ^5.5.0+1
  http: ^1.2.2
  aws_lambda_api: ^2.0.0
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/en.png
    - assets/images/logo.png
    - assets/images/fr.png
    - assets/images/de.png
    - assets/images/no-image.png
    - assets/images/home.png
    - assets/images/plants.png
    - assets/images/lexicon.png
    - assets/images/blank_bg.png
    - assets/images/settings.png
    - assets/images/lexicon/basil.png
    - assets/images/lexicon/basil_infected.jpg
    - assets/images/lexicon/basil.png
    - assets/images/lexicon/squash.jpg
    - assets/images/lexicon/squash_infected.jpg
    - assets/images/lexicon/strawberry.jpg
    - assets/images/lexicon/strawberry_mildew.jpg
    - assets/images/lexicon/tomato.jpg
    - assets/images/lexicon/tomato_late_blight.png
    - assets/images/lexicon/temperature.png
    - assets/images/lexicon/soil_humidity.png
    - assets/images/lexicon/air_humidity.png
    - assets//lang/en.json
    - assets/lang/fr.json
    - assets/lang/de.json
    - assets/splash_anim.json
  
# flutter_native_splash-acceptance.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/blank_bg.png
  branding: assets/images/blank_bg.png
  color_dark: "#121212"
  image_dark: assets/images/blank_bg.png
  branding_dark: assets/images/blank_bg.png
  android_12:
    image: assets/images/blank_bg.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/blank_bg.png
    icon_background_color_dark: "#121212"
  web: false