name: olaf

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Updated to a more recent SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # UI components
  auto_size_text: ^3.0.0
  fading_edge_scrollview: ^4.1.1
  horizontal_blocked_scroll_physics: ^4.0.1
  google_fonts: ^6.2.1
  fl_chart: ^0.71.0
  lottie: ^3.1.2
  
  # State management
  flutter_riverpod: ^2.0.0
  equatable: ^2.0.5
  
  # Device features
  camera: ^0.11.0+1
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
  # Storage & Preferences
  shared_preferences: ^2.2.3
  
  # AWS & Amplify (consolidated section)
  amplify_flutter: ^2.3.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_api: ^2.0.0
  amplify_storage_s3: ^2.3.0
  amazon_cognito_identity_dart_2: ^3.1.1
  
  # AWS Services
  aws_dynamodb_api: ^2.0.0
  aws_lambda_api: ^2.0.0
  
  # Networking
  dio: ^5.5.0+1
  http: ^1.2.2
  
  # Utils
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3  # Moved to dev_dependencies as it's a build-time tool
  flutter_native_splash: ^2.4.0    # Moved to dev_dependencies as it's a build-time tool

# Flutter config
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/lang/
    - assets/images/
    - assets/images/lexicon/
    - assets/images/dashboard/
    - assets/images/no-image.png
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/blank_bg.png
  branding: assets/images/blank_bg.png
  color_dark: "#121212"
  image_dark: assets/images/blank_bg.png
  branding_dark: assets/images/blank_bg.png
  android_12:
    image: assets/images/blank_bg.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/blank_bg.png
    icon_background_color_dark: "#121212"
  web: false